base: &base
  JSON_AS_ASCII: False
  REFRESH_TIME: 3600 # 60 * 60
  SECRET_KEY: '5a8e43810ef2d0de40e5f4b86d791f6c'
  LOG_PATH: './logs' # 相对于启动文件的位置，即manage.py文件所在目录

production:
  <<: *base

development:
  <<: *base
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:1qaz@WSX@39.104.168.95:3308/ashadow'
  SQLALCHEMY_ECHO: False
  # 默认为True，会追踪对象的修改并发送信号，需要额外的内存
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  # amqp协议默认使用librabbitmq，如果没安装librabbitmq则使用pyamqp
  CELERY_BROKER_URL: 'amqp://admin:rabbit123@39.104.168.95:5672//'
  CELERY_BACKEND: 'amqp://admin:rabbit123@39.104.168.95:5672//'
  HOST: '0.0.0.0'
  PORT: 5000